// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSp7TfYEmZbbfa2gr5jGNgChD0OotCdhk',
    appId: '1:507921047817:web:1f5567f27adb8ce8abb3d8',
    messagingSenderId: '507921047817',
    projectId: 'filmswipee',
    authDomain: 'filmswipee.firebaseapp.com',
    databaseURL: 'https://filmswipee-default-rtdb.firebaseio.com',
    storageBucket: 'filmswipee.firebasestorage.app',
    measurementId: 'G-YBC2EB1LYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWOwQFQdWJKaoEjcEGEWGifwld0Sl2l8E',
    appId: '1:507921047817:android:4200668e87b055edabb3d8',
    messagingSenderId: '507921047817',
    projectId: 'filmswipee',
    databaseURL: 'https://filmswipee-default-rtdb.firebaseio.com',
    storageBucket: 'filmswipee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXGGA5rxPr6VU0yccR4THc6qo3gvBX6Fo',
    appId: '1:507921047817:ios:328af7df839bc321abb3d8',
    messagingSenderId: '507921047817',
    projectId: 'filmswipee',
    databaseURL: 'https://filmswipee-default-rtdb.firebaseio.com',
    storageBucket: 'filmswipee.firebasestorage.app',
    iosBundleId: 'com.roastbattle.aiRoastBattle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXGGA5rxPr6VU0yccR4THc6qo3gvBX6Fo',
    appId: '1:507921047817:ios:328af7df839bc321abb3d8',
    messagingSenderId: '507921047817',
    projectId: 'filmswipee',
    databaseURL: 'https://filmswipee-default-rtdb.firebaseio.com',
    storageBucket: 'filmswipee.firebasestorage.app',
    iosBundleId: 'com.roastbattle.aiRoastBattle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSp7TfYEmZbbfa2gr5jGNgChD0OotCdhk',
    appId: '1:507921047817:web:f6a2a424866759e1abb3d8',
    messagingSenderId: '507921047817',
    projectId: 'filmswipee',
    authDomain: 'filmswipee.firebaseapp.com',
    databaseURL: 'https://filmswipee-default-rtdb.firebaseio.com',
    storageBucket: 'filmswipee.firebasestorage.app',
    measurementId: 'G-WG9F0KTQNG',
  );
}
